---
- name: "PLAY 1 - demo utilisation playbook"
  # Target/Pattern  à qui s'adresse le PLAY
  hosts: all
  become: true

  vars:
    deploy_pwd: $6$password$QSrnnf58znEKU41eJcN9cgKLOp4gkp5XXR6.j1hiiS9mHH2JhLIkZVNYjSkbYypqVVZR1nlgzeDCTuFzMmpMo0

  # Déclaration du block tasks : appel des modules ansible
  tasks:
    - name: "Ajout de l'utilisateur de deploiement via ansible"
      ansible.builtin.user:
        name: deploy
        state: present
        shell: /bin/bash
        password: "{{ deploy_pwd }}"
    
    - name: "Dépose de la clé publique du ansible mgmt chez le user deploy"
      ansible.posix.authorized_key:
        user: deploy
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

    - name: "Deploiement du fichier de regle sudo pour le user deploy"
      ansible.builtin.copy:
        dest: /etc/sudoers.d/deploy
        content: "deploy ALL=(ALL) NOPASSWD:ALL"
        mode: 0440
        owner: root
        group: root