---
- name: PLAY - Demo facts
  hosts: linux

  tasks:

  # Utilisation de facts recoltes par la task automatique gathering_facts
  - name: Utilisation d'un fact
    debug:
      msg: "Serveur sur distri: {{ ansible_distribution }}"